### PR TITLE
Feature/add ref id style conversion

### PR DESCRIPTION
**Pull request by Roblinde**

### CODE REVIEW

**Comment by aKzenT** [comment]
I didn't have a chance to test it yet, but it looks good so far. I will try it this evening.

One last thing I'm currently doing in a custom converter which I think would be very useful to support in general, is to have more control over what type is created during deserialization based on the Contentful ContentType.

In my example, if I have an Items collection I want to have various types of content within the collection, each with its own content type. My vision would be to have something like a IContentTypeResolve interface that I can set on the client which takes in a content type from contentful and returns the corresponding .NET Type to deserialize into.

This should again be easy to support using JSON.NET if we add a $type property to the JSON objects returned from Contentful.

Of course we could handle this as a separate feature request. Just wanted to mention it while we are working on deserialization anyway.

**Comment by Roblinde** [comment]
Great, looking forward to feedback.

A separate feature request would be great for that, I'll add an issue so as to not forget about it. In general the suggestion sounds great. It could probably be beneficial in many scenarios where you get mixed content back.

**Comment by aKzenT** [comment]
Hey,

sorry for the late response. I just tried the new version and it works like a charm for me!

**Comment by Roblinde** [comment]
Excellent! I'll make sure to package this and release a new version shortly.

Many thanks for the contributions.

**Pull request merged**
