### PR TITLE
Add support for cross space references without having settings

### PR DESCRIPTION
**Pull request by Roblinde**
Adds support for cross space references even if there's no cross space configured.

### CODE REVIEW

**Review by kivisto-contentful — COMMENTED** [review]
Changes look fine but the build is failing

**Comment by Roblinde** [comment]
@kivisto-contentful circle ci hasn't been working properly for years.

**Review by kivisto-contentful — DISMISSED** [review]
After discussing the failing build this all looks good to me

**Review by kivisto-contentful — APPROVED** [review]
Looks good

**Review by kivisto-contentful — APPROVED** [review]

**Pull request merged**
