### PR TITLE
feat(all): upgrade to `.NET Core 2`

### PR DESCRIPTION
**Pull request by claylaut**

### CODE REVIEW

**Comment by Roblinde** [comment]
Hi Clayton and thanks for the contribution!

Unfortunately we will not be upgrading to NetStandard 2.0. We want the package to be as compatible as possible and keeping it as NetStandard 1.4 and NetStandard 1.6 (for the aspnetcore package) achieves this.

The main issue is that by upgrading to NetStandard 2.0 .NET Core apps of v1.x will no longer be able to use the package. You can follow a discussion regarding this in this issue if you're interested: https://github.com/contentful/contentful.net/issues/108

You can also reference this table for a full overview of the compatability of the different versions NetStandard: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

I will close the pull request, but please do not be discouraged from continued contributions. Everything is appreciated and all feedback is listened to and considered carefully.

Thanks again!
Robert

**Comment by claylaut** [comment]
@Roblinde, I had issues to upgrade my application to `.NET CORE 2` due contentful library was throwing an exception about the `Microsoft.Extensions.Options.ConfigurationExtensions v1.1.2`. I will test this out tomorrow and will let you know.

**Comment by Roblinde** [comment]
Ah, please do and let me know the results. It should definitely work perfectly in a .NET Core 2 app as well.

**Comment by claylaut** [comment]
@Roblinde, please find below the issue I ran into. When I've upgraded contentful to .NET Core 2 this issue disappeared. alt text

**Comment by Roblinde** [comment]
I see, that is very strange. I'll open an issue and investigate.

**Comment by Roblinde** [comment]
Now tracking this issue in #124 

Lets continue the discussion there.

**Pull request closed without merging**
