### PR TITLE
Fix metadata deserialization in Sync* methods

### PR DESCRIPTION
**Pull request by divinci**

### CODE REVIEW

**Comment by divinci** [comment]
Hi @Roblinde let me know if you have any questions.

https://github.com/contentful/contentful.net/pull/303/commits/367f58684ef99bd4ac836cb0f8df60474ebb8266 is the test failure.

https://github.com/contentful/contentful.net/pull/303/commits/03dff5b29075f12c2f96c06a3c8d112b00a09e5a is the fix.

**Comment by divinci** [comment]
Bump @Roblinde

**Comment by Roblinde** [comment]
@divinci thank you for this! I didn't get any notifications weirdly enough, so I just missed this for the latest release :( I'll get it merged and published as soon as I get a minute.

**Comment by divinci** [comment]
Thanks @Roblinde.

**Comment by divinci** [comment]
Polite *bump* @Roblinde

**Pull request merged**
