### PR TITLE
Exposing Renderers so they can be used in Custom Renderers

### PR DESCRIPTION
**Pull request by technicaldogsbody**
I need to be able to get hold of the Renderer Collection for use in a custom link renderer, so this will expose it and allow it to be used

### CODE REVIEW

**Comment by technicaldogsbody** [comment]
example

` htmlRenderer.AddRenderer(new CustomLinkRenderer(htmlRenderer.Renderers) { Order = 10 });`

**Comment by technicaldogsbody** [comment]
https://www.technicaldogsbody.com/how-to-open-rich-text-links-in-a-new-tab-in-contentful-net for some more context

**Comment by Roblinde** [comment]
@technicaldogsbody thanks for the contribution. I'll have a look as soon as possible.

**Review by Roblinde — APPROVED** [review]

**Comment by Roblinde** [comment]
Looks like a fine way to expose the collection so you can use them in custom renderers. I'll get it in a new version and release it to nuget when I get a chance.

**Pull request merged**
