### PR TITLE
fix: impl suggest recursive fix

### PR DESCRIPTION
**Pull request by mgoudy91**

### CODE REVIEW

**Review by t-col — DISMISSED** [review]

**Comment by mgoudy91** [comment]
@Roblinde let me know what you think about this fix.

**Comment by Roblinde** [comment]
What exactly is this supposed to fix? @mgoudy91

**Comment by mgoudy91** [comment]
@Roblinde NET-140 If you're able to see the board. This was a customer-suggested fix and would definitely need validation from you to see if it makes sense

**Comment by lekimwaffle** [comment]
@mgoudy91 Hi, it was me who opened the ticket and supplied a possible fix. We've iterated further on it, because these changes only partially cover it. I'm willing to open a PR from my fork to this repository to supply the additional changes. How would you prefer me to proceed?

**Comment by kheurterincentro** [comment]
@mgoudy91  Hi, it was me who opened the ticket and supplied a possible fix. We've iterated further on it, because these changes only partially cover it. I'm willing to open a PR from my fork to this repository to supply the additional changes. How would you prefer me to proceed?

**Comment by Roblinde** [comment]
@kheurterincentro Feel free to open a PR and I can have a look!

**Comment by kheurterincentro** [comment]
It's opened #343

**Pull request merged**
