### PR TITLE
Ignore CrossSpace links when resolving links

### PR DESCRIPTION
**Pull request by jvtroyen**
Resolving CrossSpace links fails when selecting tokens for "..sys.linkType" and "..sys.id" because multiple tokens can be found in the crossSpaceEntry-json.
Since this links cannot be resolved anyway, they should be ignored.

LinkType = itemToSkip.SelectToken("$..sys.linkType").Value<string>(),
Id = itemToSkip.SelectToken("$..sys.id").Value<string>()

### CODE REVIEW

**Comment by Roblinde** [comment]
@jvtroyen What is linktype "CrossSpaceEntry". Never heard of it.

**Comment by jvtroyen** [comment]
It's a module built by a Solution Architect at Contentful (would have to look up the name), but not on the official marketplace or something.
It was suggested to us through him during a license-negotiation (I don't know the exact details) for a project and pushed through, but turned out to need some tweaking to be able to pull off.

**Comment by Roblinde** [comment]
@jvtroyen ah, yeah, I just spoke to him. Interesting. I'm a bit reluctant to add code that target api features that  aren't officially supported. If you modified this slightly to just ignore anything that isn't linktype==="Entry" or "Asset" instead, I think that'd work just as nicely.

**Comment by Roblinde** [comment]
Hi @jvtroyen 
Support for cross space referencing is now in the SDK and soon to be released with version 7.2

**Pull request closed without merging**
